### ISSUE TITLE
BUG: cannot import mtw because of "from ot import"

### ISSUE THREAD

**Issue by mathurinm** [hichamjanati/mtw#1]
```
(mtw-env) ➜  mtw git:(master) ✗ python
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:33:04) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mtw import MTW
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mathurin/workspace/mtw/mtw/__init__.py", line 1, in <module>
    from .mtw import MTW
  File "/home/mathurin/workspace/mtw/mtw/mtw.py", line 2, in <module>
    from .solver import solver
  File "/home/mathurin/workspace/mtw/mtw/solver.py", line 10, in <module>
    from .otfunctions import (barycenterkl, barycenterkl_img, barycenterkl_log,
  File "/home/mathurin/workspace/mtw/mtw/otfunctions.py", line 6, in <module>
    from ot import emd2
ModuleNotFoundError: No module named 'ot'

@hichamjanati 
```

What is `ot` supposed to be ?

**Comment by hichamjanati** [comment]
That's the pot package https://pot.readthedocs.io/en/stable/
This dependency should be removed actually
